from __future__ import annotations

import sys
import unittest
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))


class HostArtifactGenerationTests(unittest.TestCase):
    def test_generated_host_artifacts_are_current(self) -> None:
        from host_artifacts_support import ensure_generated_host_artifacts

        report = ensure_generated_host_artifacts(check=True)
        self.assertEqual(report["status"], "PASS")
        self.assertEqual(report["stale_outputs"], [])
        self.assertGreaterEqual(len(report["artifacts"]), 10)
        for artifact in report["artifacts"]:
            with self.subTest(artifact=artifact["name"]):
                self.assertTrue(artifact["output_exists"])
                self.assertFalse(artifact["stale"])
                self.assertEqual(len(artifact["source_sha256"]), 64)
                self.assertEqual(len(artifact["output_sha256"]), 64)

    def test_generated_global_templates_include_generator_header(self) -> None:
        codex_agents = (ROOT_DIR / "packages" / "forge-codex" / "overlay" / "AGENTS.global.md").read_text(encoding="utf-8")
        gemini_global = (ROOT_DIR / "packages" / "forge-antigravity" / "overlay" / "GEMINI.global.md").read_text(encoding="utf-8")
        codex_help = (ROOT_DIR / "packages" / "forge-codex" / "overlay" / "workflows" / "operator" / "help.md").read_text(encoding="utf-8")

        self.assertIn("GENERATED FILE", codex_agents)
        self.assertIn("GENERATED FILE", gemini_global)
        self.assertIn("Generated by python scripts/generate_host_artifacts.py", codex_help)


if __name__ == "__main__":
    unittest.main()
