from __future__ import annotations

from host_artifact_manifest import generated_host_artifact_records
from host_artifact_manifest import generated_host_artifact_specs
from operator_surface_support import render_registry_placeholders


GENERATED_HEADER = "<!-- Generated by python scripts/generate_host_artifacts.py. Do not edit directly. -->"


def _selected_specs(package_names: set[str] | None = None) -> list[dict]:
    specs = generated_host_artifact_specs()
    if not package_names:
        return specs
    return [item for item in specs if item["name"] in package_names]


def _normalize(text: str) -> str:
    return text.rstrip() + "\n"


def render_generated_host_artifact(spec: dict) -> str:
    source_text = spec["source_path"].read_text(encoding="utf-8")
    source_text = render_registry_placeholders(source_text, spec["bundle"], context=spec.get("context"))
    return GENERATED_HEADER + "\n\n" + _normalize(source_text)


def stale_outputs(package_names: set[str] | None = None) -> list[dict[str, object]]:
    stale: list[dict[str, object]] = []
    for spec in _selected_specs(package_names):
        output_path = spec["output_path"]
        actual = output_path.read_text(encoding="utf-8") if output_path.exists() else None
        expected = render_generated_host_artifact(spec)
        if actual == expected:
            continue
        stale.append(
            {
                "name": spec["name"],
                "path": str(output_path),
                "stale": True,
                "exists": output_path.exists(),
            }
        )
    return stale


def apply_generated_host_artifacts(package_names: set[str] | None = None) -> list[str]:
    updated: list[str] = []
    for spec in _selected_specs(package_names):
        output_path = spec["output_path"]
        expected = render_generated_host_artifact(spec)
        actual = output_path.read_text(encoding="utf-8") if output_path.exists() else None
        if actual == expected:
            continue
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(expected, encoding="utf-8")
        updated.append(str(output_path))
    return updated


def ensure_generated_host_artifacts(*, check: bool, package_names: set[str] | None = None) -> dict:
    selected_specs = _selected_specs(package_names)
    selected_names = {item["name"] for item in selected_specs}
    bundle_names = {item["bundle"] for item in selected_specs}
    stale = stale_outputs(package_names)
    stale_names = {item["name"] for item in stale}
    records = [item for item in generated_host_artifact_records(bundle_names) if item["name"] in selected_names]
    for item in records:
        item["stale"] = item["name"] in stale_names
    if check and stale:
        return {
            "status": "FAIL",
            "mode": "check",
            "artifacts": records,
            "stale_outputs": stale,
            "updated_outputs": [],
        }
    updated = apply_generated_host_artifacts(package_names) if not check else []
    refreshed_stale = stale_outputs(package_names) if not check else stale
    refreshed_stale_names = {item["name"] for item in refreshed_stale}
    refreshed_records = [item for item in generated_host_artifact_records(bundle_names) if item["name"] in selected_names]
    for item in refreshed_records:
        item["stale"] = item["name"] in refreshed_stale_names
    return {
        "status": "PASS",
        "mode": "check" if check else "apply",
        "artifacts": refreshed_records,
        "stale_outputs": refreshed_stale,
        "updated_outputs": updated,
    }


def format_report(report: dict) -> str:
    lines = [
        "Forge Host Artifact Generation",
        f"- Status: {report['status']}",
        f"- Mode: {report['mode']}",
    ]
    if report["updated_outputs"]:
        lines.append("- Updated outputs:")
        for path in report["updated_outputs"]:
            lines.append(f"  - {path}")
    else:
        lines.append("- Updated outputs: (none)")
    if report["stale_outputs"]:
        lines.append("- Stale outputs:")
        for item in report["stale_outputs"]:
            lines.append(f"  - {item['path']}")
    else:
        lines.append("- Stale outputs: (none)")
    return "\n".join(lines)
